language: node_js                                                             
node_js:
  - '8'
  - '7'
cache:
  directories:
    - $HOME/.npm
    - node_modules
before_install:
  - 'npm install --global npm@5.2.0'
after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'